name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env: 
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                nodejs-version: [18, 20]
                os: [ubuntu-latest, windows-latest]
                exclude:
                    - os: windows-latest
                      nodejs-version: 18
                    - os: windows-latest
                      nodejs-version: 20
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.nodejs-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs-version }}

        - name: cache_node_modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test

        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result-${{ matrix.os }}-${{ matrix.nodejs-version }}
            path: test-results.xml

    code-coverage:

        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: cache_node_modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

        - name: Install Dependencies
          run: npm install
    
        - name: Code Coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Coverage Report
          uses: actions/upload-artifact@v4
          with:
            name: Coverage-Report
            path: coverage
            rentention-days: 5
    
    docker:
        name: Containerization
        runs-on: ubuntu-latest
        permissions:
            packages: write
        needs: [unit-testing, code-coverage]

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_SECRET }}

        - name: GHCR login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            file: ./Dockerfile

        - name: Docker Image testing
          continue-on-error: true
          run: |
            docker images
            docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI='mongodb+srv://supercluster.d83jj.mongodb.net/superData' \
                -e MONGO_USERNAME='${{ vars.MONGO_USERNAME }}' \
                -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:latest
  
            echo Testing app is live 
            wget -qO - http://127.0.0.1:3000/planets | grep "planets" 
        
        - name: Push Docker Image to Docker Hub
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
                ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha}}
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

    deploy:
        name: Deploy to Kubernetes
        runs-on: ubuntu-latest
        if: contains(github.ref, 'feature/')
        needs: docker
        environment:
          name: dev-env
          url: https://${{ steps.fetch-ingress-host.outputs.INGRESS_HOST }}
        outputs:
          INGRESS_URL: ${{ steps.fetch-ingress-host.outputs.INGRESS_HOST }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'

        - name: Configure Kubeconfig
          uses: azure/k8s-set-context@v3
          with:
            method: 'kubeconfig'
            kubeconfig: ${{ secrets.KUBECONFIG }}

        - name: Fetch Kubernetes Cluster details
          run: |
            kubectl version --short
            echo ------------------------------------
            kubectl get nodes
        
        - name: Save ingress ip as env varaiable
          run: |
            echo  "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

        - name: Replace tokens in manifest file
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: 'kubernetes/development/*.yaml'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check files input
          run: cat kubernetes/development/*.yaml

        - name: Create MongoDB Secret
          run: |
            kubectl create secret generic mongo-credentials \
              --from-literal=mongo-uri= ${{ env.MONGO_URI }} \
              --from-literal=mongo-username='${{ vars.MONGO_USERNAME }}' \
              --from-literal=mongo-password='${{ secrets.MONGO_PASSWORD }}' \
              --namespace=${{ vars.NAMESPACE }} \
              --save-config --dry-run=client -o yaml | kubectl apply -f -
        
        - name: Deploy to Kubernetes Cluster
          run: |
            kubectl apply -f kubernetes/development

        - name: Fetch ingress host URL
          run: |
            echo "INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_ENV


    Integration-Test:
        name: Integration Testing
        runs-on: ubuntu-latest
        needs: deploy
        steps:
          - name: Test URL OUTPUT using CURL and Jq
            env:
              URL: ${{ needs.deploy.outputs.INGRESS_URL }}
            run: |
              echo $URL
              echo "--------------------------"
              curl https://$URL/live -s -k | jq -r .status | grep -i live

    prod-deploy:
        name: Deploy to Prod Kubernetes
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: docker
        environment:
          name: prod-env
          url: https://${{ steps.fetch-ingress-host.outputs.INGRESS_HOST }}
        outputs:
          INGRESS_URL: ${{ steps.fetch-ingress-host.outputs.INGRESS_HOST }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'

        - name: Configure Kubeconfig
          uses: azure/k8s-set-context@v3
          with:
            method: 'kubeconfig'
            kubeconfig: ${{ secrets.KUBECONFIG }}

        - name: Fetch Kubernetes Cluster details
          run: |
            kubectl version --short
            echo ------------------------------------
            kubectl get nodes
        
        - name: Save ingress ip as env varaiable
          run: |
            echo  "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

        - name: Replace tokens in manifest file
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: 'kubernetes/production/*.yaml'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check files input
          run: cat kubernetes/production/*.yaml

        - name: Create MongoDB Secret
          run: |
            kubectl create secret generic mongo-credentials \
              --from-literal=mongo-uri= ${{ env.MONGO_URI }} \
              --from-literal=mongo-username='${{ vars.MONGO_USERNAME }}' \
              --from-literal=mongo-password='${{ secrets.MONGO_PASSWORD }}' \
              --namespace=${{ vars.NAMESPACE }} \
              --save-config --dry-run=client -o yaml | kubectl apply -f -
        
        - name: Deploy to Kubernetes Cluster
          run: |
            kubectl apply -f kubernetes/production

        - name: Fetch ingress host URL
          run: |
            echo "INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_ENV


    Prod-Integration-Test:
        name: Prod Integration Testing
        runs-on: ubuntu-latest
        needs: prod-deploy
        steps:
          - name: Test URL OUTPUT using CURL and Jq
            env:
              URL: ${{ needs.prod-deploy.outputs.INGRESS_URL }}
            run: |
              echo $URL
              echo "--------------------------"
              curl https://$URL/live -s -k | jq -r .status | grep -i live